version: "3.9"
services:
  postgres:
    image: postgres:17.2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "frourio-template-railway-tailwind"
      TZ: "Asia/Tokyo"
    volumes:
      - database:/var/lib/postgresql/data
  # redis:
  #   image: "redis:7.2.4-alpine"
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - "./Docker/redis/data:/data"

volumes:
  database:
    driver: local
